update

diff --git a/assets/examples/proxysql.yaml b/assets/examples/proxysql.yaml
--- a/assets/examples/proxysql.yaml
+++ b/assets/examples/proxysql.yaml
@@ -3,44 +3,68 @@ kind: ProxySQL
 metadata:
   name: yuxing
 spec:
-  configImage: rumia/rds-sidecar
+  configImage: rumia/rds-sidecar:i8
   storageClassName: hostpath
   timeZone: Asia/Shanghai
-  image: rumia/proxysql:2.2.0
+  image: proxysql/proxysql:2.3.2 # #rumia/proxysql:2.2.0
   mysqlVersion: "5.7.34"
-  monitorUser: "monitor"
-  monitorPassword: "monitor_me"
-  adminUser: admin
-  adminPassword: 123456
   nodePort: 32336 #set to zero if want use random nodeport,delete this field will disable nodeport
   storageSize: 1Gi
-  readinessProbe:
-    exec:
-      command:
-        - /bin/bash
-        - -c
-        - |
-          mysqladmin ping -u${PROXYSQL_ADMIN_USER} -p${PROXYSQL_ADMIN_PASSWORD} -p6032 -h127.0.0.1 > /dev/null 2>&1
-          if [ $? != 0 ];then
-            echo "proxysql 6032 not ready"
-            exit 1
-          fi
-    initialDelaySeconds: 5
-    periodSeconds: 5
-    timeoutSeconds: 4
-    failureThreshold: 10
-  livenessProbe:
-    exec:
-        command:
-        - /bin/bash
-        - -c
-        - |
-          mysqladmin ping -u${PROXYSQL_ADMIN_USER} -p${PROXYSQL_ADMIN_PASSWORD} -p6032 -h127.0.0.1 > /dev/null 2>&1
-          if [ $? != 0 ];then
-            echo "proxysql 6032 not ready"
-            exit 1
-          fi
-    initialDelaySeconds: 5
-    periodSeconds: 5
-    timeoutSeconds: 4
-    failureThreshold: 10
+  mysqls:
+  - host: yuxing-mysql-0
+    port: 3306
+  - host: yuxing-mysql-1
+    port: 3306
+  - host: yuxing-mysql-2
+    port: 3306
+  mysqlMaxConn: 200
+  clusterMode: MGRSP
+  monitorUser:
+    username: replication
+    password: cmVwbGljYXRpb25fcGFzc3dvcmQ=
+  clusterUser:
+    username: admin
+    password: cmVwbGljYXRpb25fcGFzc3dvcmQ=
+  adminUser:
+    username: admin
+    password: cmVwbGljYXRpb25fcGFzc3dvcmQ=
+  backendUsers:
+  - username: root
+    password: MTIzNDU2
+  frontedUsers:
+  - username: root
+    password: MTIzNDU2
+    databaseTarget: "*.*"
+    domain: "%"
+    privileges:
+    - SELECT
+  # readinessProbe:
+  #   exec:
+  #     command:
+  #       - /bin/bash
+  #       - -c
+  #       - |
+  #         mysqladmin ping -u${PROXYSQL_ADMIN_USER} -p${PROXYSQL_ADMIN_PASSWORD} -p6032 -h127.0.0.1 > /dev/null 2>&1
+  #         if [ $? != 0 ];then
+  #           echo "proxysql 6032 not ready"
+  #           exit 1
+  #         fi
+  #   initialDelaySeconds: 5
+  #   periodSeconds: 5
+  #   timeoutSeconds: 4
+  #   failureThreshold: 10
+  # livenessProbe:
+  #   exec:
+  #       command:
+  #       - /bin/bash
+  #       - -c
+  #       - |
+  #         mysqladmin ping -u${PROXYSQL_ADMIN_USER} -p${PROXYSQL_ADMIN_PASSWORD} -p6032 -h127.0.0.1 > /dev/null 2>&1
+  #         if [ $? != 0 ];then
+  #           echo "proxysql 6032 not ready"
+  #           exit 1
+  #         fi
+  #   initialDelaySeconds: 5
+  #   periodSeconds: 5
+  #   timeoutSeconds: 4
+  #   failureThreshold: 10
